rabbitmq :
    image: rabbitmq:3-management   
    restart: always
    ports:
    - 4369:4369
    - 5671-5672:5671-5672
    - 15671-15672:15671-15672
    - 25672:25672

mongo:
    image: mongo
    restart: always
    ports: 
    - 27017:27017

    volumes:
    - "${PWD}/data:/data/db"

client:
    build: .
    restart: always
    volumes:
    - ${PWD}/client.py:/client.py
    links:
    - mongo:mongo
    - rabbitmq:rabbitmq
    entrypoint:
    - /entrypoint.sh

app:
    build: .
    restart: always
    volumes:
    - ${PWD}/app:/app
    links:
    - mongo:mongo
    - rabbitmq:rabbitmq
    entrypoint:
    - python
    - /app/app.py
    ports:
    - 8080:5000

