rabbitmq :
    image: rabbitmq:3-management   
    restart: always

mongo:
    image: mongo
    restart: always
    volumes:
    - "${PWD}/data:/data/db"

client:
    build: .
    restart: always
    volumes:
    - ${PWD}/client.py:/client.py
    links:
    - mongo:mongo
    - rabbitmq:rabbitmq
    entrypoint:
    - /entrypoint.sh

app:
    build: .
    restart: always
    volumes:
    - ${PWD}/app:/app
    links:
    - mongo:mongo
    - rabbitmq:rabbitmq
    entrypoint:
    - python
    - /app/app.py
    ports:
    - 8080:5000

